# NOTE: this image is never used in production (relies on Google's runtime), it only serves to mimick production as much as possible for development purposes.
FROM python:3.10.4-slim-buster

RUN pip install -U \
        black \
;
