---
name: "Create platform-tools Python artifact"

on:
  push:
    paths:
      - "treehouse/**"
      - ".github/workflows/cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2

      - name: Use default workspace (main branch)
        if: endsWith(github.ref, '/main')
        run: |
          echo "WORKSPACE=default" >> $GITHUB_ENV

      - name: Use custom workspace (feature branch)
        if: endsWith(github.ref, '/main') == false
        run: |
          echo "WORKSPACE=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Create package with dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel testresources
          pip install -e . -t dist_package --no-cache --ignore-installed
        working-directory: ./

      - name: Add platform tools code
        run: |
          cp -r treehouse dist_package/
        working-directory: ./

      - name: Zip package and remove unwanted dependencies
        run: |
          cd dist_package && zip -x "google*" -x "pyspark*" -x "*.git*" -x "*.DS_Store" -x "*.pyc" -x "*/*__pycache__*/" -x ".idea*" -x ".vscode*" -r ../platform_tools_latest.zip .
        working-directory: ./

      - name: GCP Authentication
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - name: Deploy artifact
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "platform_tools_latest.zip"
          destination: "treehouse-dataplatform-artifacts/platform_tools/latest/"

      - name: Clean up
        run: |
          rm -rf dist_package; rm platform_tools_latest.zip;

      - name: Send alert for failing apply on main
        if: endsWith(github.ref, '/main')
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
