---
name: 'CI'

on:
  pull_request:
    paths:
      - "treehouse/**"
      - "terraform/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          make test
          make cs
